name: Cloudflare Pages Preview Deployment

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  actions: read
  contents: read
  deployments: write
  pull-requests: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Preview
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Next.js App
        run: pnpm build
        env:
          NEXT_TELEMETRY_DISABLED: 1
          NODE_ENV: production

      - name: Deploy to Cloudflare Pages
        uses: andykenward/github-actions-cloudflare-pages@v2.3.2
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: admincraftwiki
          directory: .next
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-environment: 'Preview'